### ISSUE TITLE
GeoJSON-LD linked data model

### ISSUE THREAD

**Issue by todrobbins** [whosonfirst/whosonfirst-data#100]
I'm curious if there has been discussion about a [GeoJSON-LD](https://github.com/geojson/geojson-ld) model for WOF, especially as [the proposal moves forward (slowly but surely)](http://geojson.org/vocab). I understand that this would be down the road but I wanted to raise the issue.

:clap: WOF :clap:

cc @geojson @sgillies @dret

**Comment by thisisaaronland** [comment]
Hi Tod,

A few comments:

- We probably wouldn't make the "default" WOF record JSON-LD but if my reading of the spec is correct then we would endeavour to make sure that it's easy to convert a plain-vanilla GeoJSON file in to JSON-LD.

- It appears as though the only significant changes to the (GeoJSON) spec beyond making keys fully-qualified URLs are the addition of "title" and "description" keys in the Feature element. This seems a bit odd to me since a) it seems like the properties element is a better place for this sort of information b) that's the convention that everyone else has used c) it's the convention that all the tooling (Leaflet, etc.) has adopted (reading stuff from properties)

- We are still working out what the "minimal viable properties" dictionary looks like for a WOF record should be. In practice it's basically this with the understanding that depending on the record many of the values may be empty (but all the keys are present): 

```
 u'wof:belongsto': [102191575, 85633041, 136251273],
 u'wof:breaches': [],
 u'wof:concordances': {u'fct:id': u'03c06bce-8f76-11e1-848f-cfd5bf3ef515',
                       u'gn:id': 6077243,
                       u'gp:id': 3534,
                       u'tgn:id': u'7013051'},
 u'wof:country': u'CA',
 u'wof:geomhash': u'61796e06fa083f36a12ff04906e440c2',
 u'wof:hierarchy': [{u'continent_id': 102191575,
                     u'country_id': 85633041,
                     u'locality_id': 101736545,
                     u'region_id': 136251273}],
 u'wof:id': 101736545,
 u'wof:lastmodified': 1443210989,
 u'wof:megacity': 1,
 u'wof:name': u'Montr\xe9al',
 u'wof:parent_id': u'136251273',
 'wof:path': '101/736/545/101736545.geojson',
 u'wof:placetype': u'locality',
 u'wof:placetype_id': 102312317,
 u'wof:placetype_names': [],
 u'wof:scale': 1,
 u'wof:superseded_by': [],
 u'wof:supersedes': [],
 u'wof:tags': []}
```
Plus the `edtf:*` date fields which aren't in the `wof:` namespace and maybe should...

Anyway, the point is: Every key in the WOF properties dictionary is prefixed. We don't have canonical URLs for each of those prefixes yet but we will in the form of basic human-readable documentation.

So, `wof:scale` might eventually translate to `https://github.com/whosonfirst/whosonfirst-namespaces#scale`.

Does that make sense?

**Comment by thisisaaronland** [comment]
This is still a work in progress but FYI:

https://github.com/whosonfirst/whosonfirst-properties

As in:

https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof.md#id

There are probably some unknown-unknowns that will creep up in all of this but that's the work...

**Comment by todrobbins** [comment]
Thanks for the update @thisisaaronland! It's fun to see things congeal.
