### ISSUE TITLE
Denmark confused with Greenland

### ISSUE THREAD

**Issue by simonmikkelsen** [whosonfirst/whosonfirst-data#177]
On the statistics page of Mapillary they use your data. When I search for the country of Denmark (http://www.mapillary.com/map/stats?p=Denmark) it will show Denmark listed but with the flag of Greenland. When I click the link it will show Greenland.

In short, Denmark is a sovereign country. Formerly Greenland was a danish colony, but now they have a high degree of self-governance and their own parliament - with a few seats in the danish parliament.

According to my original issue https://github.com/mapillary/mapillary_issues/issues/1587 they think the error is in your data and I should report it here. I have looked at the source data, and it will probably take my hours to read enough documentation to say if they are wrong or right.

**Comment by nvkelso** [comment]
Thanks for the report, we'll have a look. Sorry about this, sounds like an error!

_Nathaniel

**Comment by thisisaaronland** [comment]
So there are three issues all compounding one another:

1) It appears as though Mapillary is using the `ne:sovereignt` property to flag parent country/empire – this is incorrect despite the fact that we (WOF) have included the ne: properties wholesale in the record.

2) `ne:sovereignt` maps to the WOF concept of "empire" [1] which is not included in the hierarchy for Greenland

3) We (WOF) haven't done a great job in articulating the order of precedence around metadata properties (say `wof:` versus `ne:`) so that's a thing we need to do.

I will update the hierarchy for Greenland shortly and start thinking about where best to record these sorts of interpretive issues. If you have thoughts or comments or feels we'd love to hear them :D

--

[1] https://github.com/whosonfirst/whosonfirst-placetypes#empire

3) We haven't done an awesome job communicating how and when to use one namespaced property

**Comment by peterneubauer** [comment]
Awesome, thanks for the update, we try to adapt at Mapillary to whatever you think is the best way.
