### ISSUE TITLE
Record hierarchies referencing invalid countries

### ISSUE THREAD

**Issue by trescube** [whosonfirst/whosonfirst-data#209]
Attached is a file containing record with hierarchies referencing invalid countries.  The file contains 2 fields:

1.  WOF id
2.  Referenced country WOF id

For example, the first entry is:

`85632567,1437509429`

Means that WOF id `85632567` has a hierarchy with country_id `1437509429` but that does not exist.  
[invalid_country_id.txt](https://github.com/whosonfirst/whosonfirst-data/files/133625/invalid_country_id.txt)

**Comment by thisisaaronland** [comment]
Who's spent too much times with Unix timestamps to recognize them a mile away...

```
php -r 'echo date("c", 1437509429);'
2015-07-21T20:10:29+00:00
```

Meanwhile `-1` is not an invalid country, per se. It means that something is easier a known-known issue and/or needs to be vetted. Which leaves us with:

```
grep -v '\-1' invalid_country_id.txt | awk -F ',' '{ print $2 }' | uniq
1437509429
85632501
85632209
85632683
85632321
```

Which is good because the first should point to Burkina Faso (85632213) and the remaining 4 should be easy to sort with a little more digging.
