### ISSUE TITLE
ÐÐ¸ÐºÐ¾Ð»Ð°ÑÐ²ÑÑÐºÐ¸Ð¹

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst/whosonfirst-data#244]
https://whosonfirst.mapzen.com/spelunker/id/102088291/#10/49.4974/23.9824

**Comment by stepps00** [comment]
Related to https://github.com/whosonfirst/whosonfirst-data/issues/292

**Comment by thisisaaronland** [comment]
It is all coming back to me, now...

Basically: The original `qs_adm2.shp` had to be converted to Latin-1 because...

```
    col = geojson.load(fh)
  File "build/bdist.linux-x86_64/egg/geojson/codec.py", line 44, in load
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 5: unexpected end of data
```

...which worked fine _except_ for counties in the Ukraine which were actually UTF-8. Because computers, right? Anyway, the solution is:

```
    col = geojson.load(fh)

    for feature in col['features']:

	props = feature['properties']

	if props.get('qs_iso_cc', '') != 'UA':
            continue

	print props['qs_a2'].encode('latin-1').decode('utf-8')
	print props['qs_a2_alt']
```

Which produces:

```
python ./wtf-ua.py qs_adm2.geojson
Ренійський
Reniis'kyi
Ялта
Yalta
Ізмаїльський
Izmail's'kyi
Кілійський
Kiliis'kyi
Бахчисарайський
```

So I will figure out how to update things shortly.

Conveniently I am pretty sure this is also the root cause of this:

https://github.com/whosonfirst/whosonfirst-www-spelunker/issues/12

@dianashk : Do you recognize/know whether names like "Кілійський" should be classified as `ukr` or `rus` ? I am guessing the former but measure twice and all that...

**Comment by thisisaaronland** [comment]
Fixed. The Spelunker might take a little while to update as caches get reset. I need to update the network JS to force refreshes somehow but that is an entirely separate issue.

![screen shot 2016-05-27 at 12 40 32](https://cloud.githubusercontent.com/assets/12658759/15619325/792c9c22-2408-11e6-9338-307308942a05.png)
![screen shot 2016-05-27 at 12 41 12](https://cloud.githubusercontent.com/assets/12658759/15619324/792aae3a-2408-11e6-8646-b0a8d65182d0.png)
