### ISSUE TITLE
hash delimited alt names in Finland

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/whosonfirst-data#247]
we seem to have inherited the hash-delimited names from Quattroshapes:

eg. "Länsi- Ja Sisä-Suomen Avi#Västra Och Inre Finlands Rfv"

https://whosonfirst.mapzen.com/spelunker/id/404227417/#18/60.93970/20.16577

**Comment by stepps00** [comment]
Noting that this issue is occuring in all `macroregion` records in Finland

**Comment by nvkelso** [comment]
What languages are these? Which should be stored into the `wof:name` (the language spoken there), and which into a language variant?

**Comment by nvkelso** [comment]
@stepps00 Is this happening in other European countries besides Finland?

**Comment by stepps00** [comment]
@nvkelso This is only an issue for Finnish macroregions. List of affected records below:
* https://whosonfirst.mapzen.com/spelunker/search/?q=macroregion&placetype=macroregion&iso=fi#5/64.444/28.455

A starting source for the six regions in Finland:
* https://en.wikipedia.org/wiki/Regional_State_Administrative_Agency

The current name (In Finnish) essentially says `Regional State Administrative Agency for [Region Name]`. The `wof:name` should just reflect the name for that specific region, language variant could include full name in Finnish.

**Comment by nvkelso** [comment]
Those are too long and formal for the `wof:name` property. We should use `[Region Name]` only. I'm fine with your proposal for Finish variant. 

Here's another `#` name in Belgium: 

* https://whosonfirst.mapzen.com/spelunker/id/102049957

**Comment by stepps00** [comment]
According to [Wikipedia,](https://en.wikipedia.org/wiki/Provinces_of_Finland ) the following names are conventional:

* `Lapland` (English)
* `Lapin` (Finnish, where lääni is the placetype)
* `Lapplands` (Swedish, where län is the placetype)

Proposal:

* `wof:name` as **Lapin**, as this is the default local name used in this geography.
* `name:eng_x_preferred` as **Lapland**
* `name:fin_x_preferred` as **Lapin**
* `name:fin_x_variant` as **Lapin lääni**
* `name:swe_x_preferred` as **Lapplands**
* `name:swe_x_variant` as **Lapplands län**

@thisisaaronland to confirm this approach.

**Comment by hannesj** [comment]
It's a bit complicated due to the Finnish language and its usage of cases. Also läänis as a place types were dissolved in 2009 and were replaced by Aluehallintovirasto (which is never used in daily language and only in governamental work)

I would suggest the following names:

wof:name | name:eng_x_preferred | name:eng_x_variant | name:fin_x_preferred | name:fin_x_variant | name:swe_x_preferred | name:swe_x_variant
------------- | ------------------------------ | --------------------------- | ---------------------------- | -------------------------- | ------------------------------ | --------------------------
Etelä-Suomi | Southern Finland | Regional State Administrative Agency for Southern Finland | Etelä-Suomi | Etelä-Suomen aluehallintovirasto | Södra Finland | Regionförvaltningsverket i Södra Finland
Itä-Suomi | Eastern Finland | Regional State Administrative Agency for Eastern Finland | Itä-Suomi | Itä-Suomen aluehallintovirasto | Östra Finland | Regionförvaltningsverket i Östra Finland
Lappi | Lapland | Regional State Administrative Agency for Lapland | Lappi | Lapin aluehallintovirasto | Lappland | Regionförvaltningsverket i Lappland
Lounais-Suomi | Southwestern Finland | Regional State Administrative Agency for Southwestern Finland | Lounais-Suomi | Lounais-Suomen aluehallintovirasto | Sydvästra Finland | Regionförvaltningsverket i Sydvästra Finland
Länsi ja Sisä-Suomi | Western and Inland Finland | Regional State Administrative Agency for Western and Inland Finland | Länsi ja Sisä-Suomi | Länsi- ja Sisä-Suomen aluehallintovirasto | Västra och Inre Finland | Regionförvaltningsverket i Västra och Inre Finland
Pohjois-Suomi | Northern Finland | Regional State Administrative Agency for Northern Finland | Pohjois-Suomi | Pohjois-Suomen aluehallintovirasto | Norra Finland | Regionförvaltningsverket i Norra Finland
Åland | Åland | State Department of Åland | Ahvenanmaa | Ahvenanmaan valtionvirasto | Åland | Statens ämbetsverk på Åland

**Comment by nvkelso** [comment]
Thank you, @hannesj!

**Comment by hugovk** [comment]
Something similar was reported for Finland region names in #59 and fixed in PR #80 (and also #91 fixed in PR #96). 

PR #78 fixed something similar for Wales in #60 which has both English and Welsh official names.

Relevant to this issue these questions: https://github.com/whosonfirst/whosonfirst-data/pull/78#issuecomment-140210553
And these answers: https://github.com/whosonfirst/whosonfirst-data/pull/78#issuecomment-142146472

 * The most-commonly used name in English was put in `wof:name`, either an English name ("Lapland") or a Finnish one if there was no English (""Uusimaa"")  (e.g. https://github.com/whosonfirst/whosonfirst-data/pull/80/commits/a41ac6f634a86211acab6d1f12df10c17cae8d0b)
 * No `name:eng_p`
 * Finnish and Swedish names in `name:fin_p` and `name:swe_p`
 * Add `"wof:lang": [ "eng", "fin", "swe" ],` (e.g. https://github.com/whosonfirst/whosonfirst-data/pull/80/commits/1f617169dc3836dfddfbc5cc91776180084657aa)

**Comment by thisisaaronland** [comment]
All of this seems fine, with a couple provisos:

1. All teh languages and variants!
2. We are standardizing `wof:name` to be 7-bit ASCII transliterated English; this is going to take some time and effort to complete because it's a hard problem. See also: issue #183 
3. We need to complete the work to backfill `wof:lang` on all records to indicate the languages spoken in a given spot. That's on me so I will try to get that sorted out sooner than later.

Per #3 I would prefer to simply include an unordered list of language codes in `wof:lang` rather than try to encode/enforce/arbitrate an order of precedence. I am from Canada so...

That said, it would be weird (or perhaps just awkward) to localize a map in/of Finland with Swedish names so I would welcome feedback and commentary...

**Comment by thisisaaronland** [comment]
FYI: https://github.com/whosonfirst/whosonfirst-data/issues/290

**Comment by nvkelso** [comment]
For map display, I'd like to know what the locals call their thing (as in the locals in the locality and region), and also what the "national" language(s) are.

**Comment by thisisaaronland** [comment]
That sounds like a job for the `mz:` namespace :-)

Just let me know what you want the keys to be named.

**Comment by thisisaaronland** [comment]
Alternately, looking at the Libpostal dump it's basically divided in to two buckets: official languages and languages that are also spoken. So we could do the following:

`wof:lang` <-- effectively `wof:lang_x_preferred` (by locals) so perhaps it's better to just be explicit about it...
`wof:lang_x_official`
 `wof:lang_x_spoken` <-- inclusive of `wof:lang_x_official`

**Comment by thisisaaronland** [comment]
Related: 

https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof.md#lang

**Comment by thisisaaronland** [comment]
Work in progress – official v. spoken languages – these are only set countries, as of this writing:

![screen shot 2016-05-16 at 18 09 50](https://cloud.githubusercontent.com/assets/12658759/15308406/b216f1b0-1b91-11e6-8ca2-f1a444c47ba1.png)
![screen shot 2016-05-16 at 18 10 19](https://cloud.githubusercontent.com/assets/12658759/15308405/b2169620-1b91-11e6-8e75-dc914885db5c.png)
![screen shot 2016-05-16 at 18 11 10](https://cloud.githubusercontent.com/assets/12658759/15308407/b218ede4-1b91-11e6-8f9b-e0acdfb6a94c.png)

**Comment by hugovk** [comment]
> That said, it would be weird (or perhaps just awkward) to localize a map in/of Finland with Swedish names so I would welcome feedback and commentary...

Not for a Swedish-language user/Swedish-language map.

---

> For map display, I'd like to know what the locals call their thing (as in the locals in the locality and region), and also what the "national" language(s) are.

Generally, yes, but there are also English names I as an English-language user would probably want to see.

If I look at Finland on the English version of Google Maps, 
 * the predominantly Finnish-speaking places are labelled with Finnish names,
 * the predominantly Swedish-speaking places are labelled with Swedish names (e.g. Ingå, Karis, Raseborg, Åland),
 * I'd also expect English region names (Lapland) where available.

If I switch to the Finnish version: https://www.google.com/?hl=fi I see 
 * both Finnish and Swedish names on the map (not unusual, road signs are like this),
 * Finnish comes first for predominantly Finnish-speaking places (Helsinki Helsingfors), 
 * Swedish for predominantly Swedish-speaking places (Karis Karjaa),
 * just Finnish if there's no Swedish name (Kotka), and
 * just Swedish if there's no Finnish name (Föglö).

---

> We are standardizing `wof:name` to be 7-bit ASCII transliterated English; this is going to take some time and effort to complete because it's a hard problem.

As long as there's not going to be a map showing Jyvaskyla and Toolo instead of Jyväskylä and Töölö. These are different letters entirely and not accents, and it'll look really daft to locals.

**Comment by hannesj** [comment]
> > We are standardizing wof:name to be 7-bit ASCII transliterated English; this is going to take some time and effort to complete because it's a hard problem.

> As long as there's not going to be a map showing Jyvaskyla and Toolo instead of Jyväskylä and Töölö. These are different letters entirely and not accents, and it'll look really daft to locals.

I strongly agree. It is like asking how to write the word `London` without using the letter `o`.

**Comment by thisisaaronland** [comment]
Oh, definitely (Töölö instead of Toolo, and so on).

The ASCII version is simply to have a baseline, globally.

Part of the work to finish up all the `wof:lang` work is to allow us to better introspect the data to ensure that we have corresponding `name:LANG_x_preferred` variants for each record.

**Comment by stepps00** [comment]
Regarding @nvkelso comment https://github.com/whosonfirst/whosonfirst-data/issues/247#issuecomment-217993973...

> Those are too long and formal for the wof:name property. We should use [Region Name] only. I'm fine with your proposal for Finish variant. 

The `wof:name` field was edited for [Brussel-Hoofstad](https://whosonfirst.mapzen.com/spelunker/id/102049957) record in commit e06c658b7859b06a3a7e2ff6cdd8509313121330

**Comment by stepps00** [comment]
[This table](https://github.com/whosonfirst/whosonfirst-data/issues/247#issuecomment-218681534) was used in #99 to update the `variant` and `preferred` names for `region` and `macroregion` records. The `#` issue in the `wof:name` field does not affect any additional records.

Closing this issue in favor of #99.
