### ISSUE TITLE
Change name of Norther, Fiji to Northern Division

### ISSUE THREAD

**Issue by dianashk** [whosonfirst/whosonfirst-data#248]
The name needs to be updated, but also the geometry looks really strange there.

https://whosonfirst.mapzen.com/spelunker/id/85671179/#2/-16.6/0.0
![whosonfirst-spelunker-1460566791502](https://cloud.githubusercontent.com/assets/5446511/14502106/aad5340e-0177-11e6-9894-26dda1f5ea94.png)

**Comment by nvkelso** [comment]
Please note that `u'qs:type': u'Division',` does provide this granularity, and `Northern` alone is prefered for map display. Suggest providing a search label name that provides `Northern Division`.

I think the two shapes (that look like separate, duplicate shapes) are from Leaflet wrapping over the ±180 line (it's drawing the same shape twice since that geography is visible twice in the map view.
