### ISSUE TITLE
missing name

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/whosonfirst-data#310]
https://whosonfirst.mapzen.com/spelunker/id/404529555

**Comment by stepps00** [comment]
Either:

A. Change `wof:name` to [Danish Straits](https://en.wikipedia.org/wiki/Danish_straits)  
or

B. Disect the polygon into _at least_ three individual polygons to represent each body of water in that area ([Great Belt](https://en.wikipedia.org/wiki/Great_Belt), [Little Belt](https://en.wikipedia.org/wiki/Little_Belt), and [Øresund](https://en.wikipedia.org/wiki/%C3%98resund))

Will likely go with option A because the Danish Straits actually contain more than just those three bodies of water.

https://en.wikipedia.org/wiki/Danish_straits

**Comment by nvkelso** [comment]
I prefer Danish Straits. (The marinearea features are meant to be macro in scope.)

**Comment by dianashk** [comment]
@missinglink, did you find this in Mapzen Search or just happened to stumble upon it when browsing the Spelunker? Just want to know how `placetype`=`marinearea` would end up inside our index.
