### ISSUE TITLE
Spot checking UK polygons

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/whosonfirst-data#329]
I just saw that UK postcode data was imported, this is awesome!

When I spot-chekcing some postcodes I know, actually they were both wrong :(
not sure if this is indicative of the data as-a-whole or just that I only know difficult postcodes :)

N17EG, Hoxton, London - has a lat/lon of 0,0
https://whosonfirst.mapzen.com/spelunker/id/470995865

E81DN, Hackney, London - Polygon data is an oval and is located in Dorset, not London
https://whosonfirst.mapzen.com/spelunker/id/454530689
https://whosonfirst.mapzen.com/spelunker/id/454531999 < also in E8 London

---

@aaron @nvkelso I noticed two links at the top right corner of wikipedia eg. https://en.wikipedia.org/wiki/E_postcode_area

which say "Postcode district boundaries: Bing / Google" and when you click the links it shows the boundary data on a Bing/ Google base map.

do you know where this data is sourced from? It seems to be coming from Wikipedia?
https://en.wikipedia.org/w/index.php?title=Template:Attached_KML/E_postcode_area&action=raw&ignoreoptin=1
[edit] they seem to only be the postcode prefixes :(

**Comment by thisisaaronland** [comment]
Postal code data for the UK was imported _without_ _any_ geometries, a while back.

The majority still lack coordinate data:

https://whosonfirst.mapzen.com/spelunker/placetypes/postalcode/?iso=gb

The 800K records updated over the weekend are from the Ordnance Survey:

https://whosonfirst.mapzen.com/spelunker/placetypes/postalcode/?iso=gb&exclude=nullisland

There is another equally large bag of postal codes waiting to be imported pending some answers from OS.

Things like this:

https://whosonfirst.mapzen.com/spelunker/id/454531999/

Don't have a geometry but they have been slotted in to a hierarchy by way of their GeoPlanet (the initial import source) parent id and the map is zooming out to that parent. Parent features are always blue in the Spelunker. It would be worth adding some copy to the site for situations like this.

**Comment by missinglink** [comment]
oh I see thanks, yep I was getting confused by the map view.

if there a simple way of detecting placeholder geometry like this or should I just be discarding anything at 0,0?

**Comment by thisisaaronland** [comment]
There is no placeholder geometry in the individual record. The parent ID/geometry is a display-only thing for the Spelunker.

The decisions of when/where to exclude records are left up to consumer applications. For the purposes of a geocode, yeah – it's probably best to skip things with `0,0` coordinates unless you want to derive a "more like this than the entirety of the globe" geometry from its parent ID.

This is what we do for Canada where only the 1600 FSA records have geometries. In the absense of any other open data the remaining 800K geometries are inferred from their parent FSA and flagged as `mz:is_approximate` :

https://whosonfirst.mapzen.com/spelunker/id/521999605/

We haven't done this for other postalcodes since a locality or neighbourhood is not the same as an FSA (or equivalent) but approximate geometries are a thing we are thinking about since it's better than Null Island...

https://whosonfirst.mapzen.com/spelunker/nullisland/?&locality_id=101752283
