### ISSUE TITLE
Spell out abbreviations in region names

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-data#62]
Make sure abbreviations are spelled out:
Pakistan	F.A.T.A.	85675749
Pakistan	F.C.T.	85675741
Pakistan	N.W.F.P.	85675763
UNDOF	85681385

**Comment by hugovk** [comment]
If I was to PR this, am I correct in doing the following?

 * editing the files to change, for example, `"qs:a1":"N.W.F.P."` to `"qs:a1":"North-West Frontier Province"`
 * don't change, for example, `name:eng_a":["NWFP"],"` (is `eng_a` an abbreviation for "English abbreviation? Are these listed somewhere?)
 * update `wof:lastmodified":1441062914` to the Unix timestamp of now

**Comment by thisisaaronland** [comment]
This is great and super-helpful for us to understand how/what to ask of people when submitting pull requests. Not least is a document people (like you) can consult, so we'll write that shortly!

The names look good but can you add the abbreviations to a "name:eng_a" key, as you've indicated above. I will draft a whosonfirst-names repo/doc tomorrow with all the details for people to check.

In the meantime, all the "qs:*" properties should remain untouched since those are Quattroshapes specific. Again, that's a thing for us to document.

As for lastmod, your timestamp is fine. We have a series of tools for validating records and "exporting" them which does things like timestamps but ... again, those need to be documented.

Also, I think we're just going to throw filesize concerns to the wind and indent all the GeoJSON if only to make diffs easier to check :-)

**Comment by hugovk** [comment]
@thisisaaronland Done: https://github.com/whosonfirst/whosonfirst-data/issues/76
